-- ========================================================
-- SCRIPT DE CRIAÇÃO DO BANCO DE DADOS SUPABASE (BAZAR / PDV)
-- Cole este script no SQL Editor do seu painel Supabase
-- ========================================================

-- 1. TABELA DE PRODUTOS
CREATE TABLE IF NOT EXISTS public.products (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  name TEXT NOT NULL,
  price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  category TEXT DEFAULT 'Geral',
  stock INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TABELA DE VENDAS
CREATE TABLE IF NOT EXISTS public.sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  total NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  discount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  payment_method TEXT NOT NULL,
  customer TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TABELA DE ITENS DA VENDA
CREATE TABLE IF NOT EXISTS public.sale_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sale_id BIGINT REFERENCES public.sales(id) ON DELETE CASCADE,
  product_id TEXT,
  name TEXT NOT NULL,
  price NUMERIC(10, 2) NOT NULL,
  qty INT NOT NULL DEFAULT 1
);

-- 4. TABELA DE SESSÕES DE CAIXA (ABERTURA E FECHAMENTO)
CREATE TABLE IF NOT EXISTS public.cash_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  opened_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  closed_at TIMESTAMPTZ,
  initial_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  final_amount NUMERIC(10, 2),
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
  notes TEXT
);

-- 5. TABELA DE MOVIMENTAÇÕES DE CAIXA (SUPRIMENTO E SANGRIA)
CREATE TABLE IF NOT EXISTS public.cash_movements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID REFERENCES public.cash_sessions(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('suprimento', 'sangria')),
  amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  description TEXT,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- ========================================================
-- DESABILITAR OU CONFIGURAR RLS (Row Level Security)
-- Permite leitura e escrita via Anon Key para desenvolvimento rápido
-- ========================================================

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sale_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cash_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cash_movements ENABLE ROW LEVEL SECURITY;

-- Políticas de acesso livre para a chave anon (Desenvolvimento / Produção simples)
CREATE POLICY "Permitir tudo para produtos" ON public.products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir tudo para vendas" ON public.sales FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir tudo para itens de vendas" ON public.sale_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir tudo para caixa" ON public.cash_sessions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir tudo para movimentacoes de caixa" ON public.cash_movements FOR ALL USING (true) WITH CHECK (true);

-- Habilitar chamadas Realtime (opcional para sincronização ao vivo)
ALTER PUBLICATION supabase_realtime ADD TABLE public.products;
ALTER PUBLICATION supabase_realtime ADD TABLE public.sales;
ALTER PUBLICATION supabase_realtime ADD TABLE public.cash_sessions;

-- ========================================================
-- DADOS INICIAIS (OPCIONAL)
-- ========================================================
INSERT INTO public.products (id, name, price) VALUES
  ('1', 'Camiseta Básica', 29.90),
  ('2', 'Calça Jeans', 89.90),
  ('3', 'Tênis Casual', 149.90),
  ('4', 'Meia Algodão (par)', 9.90),
  ('5', 'Cinto Couro', 39.90)
ON CONFLICT (id) DO NOTHING;
